<?php
	session_start();
	// Redirect the user to login page if he is not logged in.
	if(!isset($_SESSION['loggedIn'])){
		header('Location: login.php');
		exit();
	}

	
	require_once('inc/config/constants.php');
	require_once('inc/config/db.php');
	require_once('inc/header.html');
?>
  <body>
<?php
	require 'inc/navigation.php';
?>
	<div class="sidebar">
	<div class="col-lg-2">
		<h1 class="my-4"></h1>
			<div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
			  <a class="nav-link active" id="v-pills-dashboard-tab" data-toggle="pill" href="#v-pills-dashboard" role="tab" aria-controls="v-pills-dashboard" aria-selected="true">Dashboard</a>
			  <a class="nav-link" id="v-pills-item-tab" data-toggle="pill" href="#v-pills-item" role="tab" aria-controls="v-pills-item" aria-selected="false">Item</a>
			  <a class="nav-link" id="v-pills-search-tab" data-toggle="pill" href="#v-pills-search" role="tab" aria-controls="v-pills-search" aria-selected="false">Search</a>
			  <a class="nav-link" id="v-pills-reports-tab" data-toggle="pill" href="#v-pills-reports" role="tab" aria-controls="v-pills-reports" aria-selected="false">Reports</a>
			</div>
		</div>
	</div>
    <!-- Page Content -->
    <div class="container-fluid page-content">
	  <div class="row">
		<div class="col-lg-10">
			<div class="tab-content" id="v-pills-tabContent">
				<div class="tab-pane fade show active" id="v-pills-dashboard" role="tabpanel" aria-labelledby="v-pills-dashboard-tab">
					<div class="card card-outline-secondary my-4 count">
						<div class="card-header">Dashboard</div>
						<div class="counters">
				  			<div class="cards">
								<div class="card-head">Devices</div>
								<div class="card-details" id="devices"></div>
							</div> 
							<div class="cards">
								<div class="card-head">Device Type</div>
								<div class="card-details">
									<h4 class="count_title">Desktop: <b id="desktop"></b></h4>
									<h4 class="count_title">Laptop: <b id="laptop"></b></h4>
									<h4 class="count_title">All in One: <b id="allInOne"></b></h4>
								</div>
							</div>
							<div class="cards">
								<div class="card-head">Activated Windows</div>
								<div class="card-details" id="os_status"></div>
							</div> 
							<div class="cards">
								<div class="card-head">Antivirus Status</div>
								<div class="card-details" id="eset"></div>
							</div>
						</div> 
					</div>
				</div>
			  	<div class="tab-pane fade" id="v-pills-item" role="tabpanel" aria-labelledby="v-pills-item-tab">
					<div class="card card-outline-secondary my-4">
				  		<div class="card-header">Item Details</div>
				  		<div class="card-body">
							<ul class="nav nav-tabs" role="tablist">
								<li class="nav-item">
									<a class="nav-link active" data-toggle="tab" href="#itemDetailsTab">Item</a>
								</li>
						<!--<li class="nav-item">
							<a class="nav-link" data-toggle="tab" href="#itemImageTab">Upload Image</a>
						</li> -->
							</ul>
					
					<!-- Tab panes for item details and image sections -->
					<div class="tab-content">
						<div id="itemDetailsTab" class="container-fluid tab-pane active">
							<br>
							<!-- Div to show the ajax message from validations/db submission -->
							<div id="itemDetailsMessage"></div>
							<form>
							  <div class="form-row">
								<div class="form-group col-md-3">
									<!-- Product Code ID generation and population -->
								  <label for="productID">Product ID -- Autogenerated</label>
								  <input class="form-control invTooltip" type="number" readonly  id="productID" name="productID" title="This will be auto-generated when you add a new item">
								</div>
								<!-- Device Code -->
								<div class="form-group col-md-3" style="display:inline-block">
								  <label for="deviceCode">Device Code<span class="requiredIcon">*</span></label>
								  <input type="text" class="form-control" name="deviceCode" id="deviceCode" autocomplete="off">
								  <div id="deviceCodeSuggestionsDiv" class="customListDivWidth"></div>
								</div>
								<!-- Staff Name Div -->
								<div class="form-group col-md-3" style="display:inline-block">
								  <label for="staffName">Staff Name<span class="requiredIcon">*</span></label>
								  <input type="text" class="form-control" name="staffName" id="staffName" autocomplete="off">
								  <div id="staffNameSuggestionsDiv" class="customListDivWidth"></div>
								</div>
							  </div>
							  <div class="form-row">
								  <!-- State Div -->
							  <div class="form-group col-md-2">
									<label for="office">Location<span class="requiredIcon">*</span></label>
									<select id="office" name="office" class="form-control chosenSelect">
											<option selected value="">Select Office</option>
											<option value="Abia">Abia</option>
											<option value="Adamawa">Adamawa</option>
											<option value="Akwa Ibom">Akwa Ibom</option>
											<option value="Anambra">Anambra</option>
											<option value="Apapa">Apapa</option>
											<option value="Bauchi">Bauchi</option>
											<option value="Bayelsa">Bayelsa</option>
											<option value="Benue">Benue</option>
											<option value="Borno">Borno</option>
											<option value="Cross River">Cross River</option>
											<option value="Delta">Delta</option>
											<option value="Ebonyi">Ebonyi</option>
											<option value="Edo">Ebonyi</option>
											<option value="Ekiti">Ekiti</option>
											<option value="Enugu">Enugu</option>
											<option value="FCT 1">FCT 1</option>
											<option value="FCT 2">FCT 2</option>
											<option value="Head Office">Head Office</option>
											<option value="Ikeja">Ikeja</option>
											<option value="Imo">Imo</option>
											<option value="Jigawa">Jigawa</option>
											<option value="Kaduna">Kaduna</option>
											<option value="Kano">Kano</option>
											<option value="Katsina">Katsina</option>
											<option value="Kebbi">Kebbi</option>
											<option value="Kogi">Kogi</option>
											<option value="Kwara">Kwara</option>
											<option value="LagosZonalOffice">Lagos Zonal Office</option>
											<option value="Lagos Main">Lagos Main</option>
											<option value="Nasarawa">Nasarawa</option>
											<option value="Niger">Niger</option>
											<option value="Ogun">Ogun</option>
											<option value="Ondo">Ondo</option>
											<option value="Osun">Osun</option>
											<option value="Oyo Zonal">Oyo Zonal</option>
											<option value="Oyo">Oyo</option>
											<option value="Plateau">Plateau</option>
											<option value="Rivers">Rivers</option>
											<option value="Sokoto">Sokoto</option>
											<option value="Taraba">Taraba</option>
											<option value="Yobe">Yobe</option>
											<option value="Zamfara">Zamfara</option>
									</select>
								  </div>

							  	<!-- Department Div -->								  
								  <div class="form-group col-md-2">
									<label for="department">Groups/Offices<span class="requiredIcon">*</span></label>
									<select id="department" name="department" class="form-control chosenSelect">
										<option value="0">Select</option>
										<option value="Board Secretary">Board Secretary</option>
										<option value="Corporate Comms">Corporate Comms</option>
										<option value="FOC">FOC</option>
										<option value="FINCON">FINCON</option>
										<option value="HR">HR</option>
										<option value="ICT">ICT</option>
										<option value="Internal Audit">Audit</option>
										<option value="ICC">ICC</option>
										<option value="IRO">IRO</option>
										<option value="Legal">Legal</option>
										<option value="Loans Admin">Loan Admin</option>
										<option value="Loan and Mortgages">Loan and Mortgages</option>
										<option value="NHF">NHF</option>
										<option value="Procurement">Procurement</option>
										<option value="Project Finance">Project Finance</option>
										<option value="Remedial Management">Remedial Management</option>
										<option value="Risk">Risk</option>
										<option value="SA TO MD">SA TO MD</option>
										<option value="Special Products">Special Products</option>
										<option value="Support Services">Support Services</option>
										<option value="Treasury">Treasury</option>
									</select>
								  </div>
									<!-- Device Type Div -->
								  <div class="form-group col-md-2">
									<label for="deviceType">Device Type<span class="requiredIcon">*</span></label>
									<select id="deviceType" name="deviceType" class="form-control chosenSelect">
										<option value="0">Select</option>
										<option value="Desktop">Desktop</option>
										<option value="Laptop">Laptop</option>
										<option value="All in One">All in One</option>
									</select>
								  </div>
								  <!-- Device RAM Div -->
								  <div class="form-group col-md-2">
									<label for="deviceRam">Device RAM<span class="requiredIcon">*</span></label>
									<select id="deviceRam" name="deviceRam" class="form-control chosenSelect">
										<option value="0">Select</option>
										<option value="2GB">2GB</option>
										<option value="4GB">4GB</option>
										<option value="6GB">6GB</option>
										<option value="8GB">8GB</option>
										<option value="16GB">16GB</option>
									</select>
								  </div>
								  <!-- Device Storage Div -->
								  <div class="form-group col-md-2">
									<label for="deviceStorage">Device Storage<span class="requiredIcon">*</span></label>
									<select id="deviceStorage" name="deviceStorage" class="form-control chosenSelect">
										<option value="0">Select</option>
										<option value="500GB">500GB</option>
										<option value="1TB">1TB</option>
									</select>
								  </div>
							  </div>

							  <div class="form-row">								
								  <!-- Windows License Div -->
								  <div class="form-group col-md-3">
									<label for="os">Operating System<span class="requiredIcon">*</span></label>
									<select id="os" name="os" class="form-control chosenSelect">
										<option value="0">Select</option>
										<option value="Windows XP">Windows XP</option>
										<option value="Windows Vista">Windows Vista</option>
										<option value="Windows 7">Windows 7</option>
										<option value="Windows 8">Windows 8</option>
										<option value="Windows 8.1">Windows 8.1</option>
										<option value="Windows 10">Windows 10</option>
										<option value="Windows 11">Windows 11</option>
									</select>
								  </div>
							  	<div class="form-group col-md-3">
									<label for="osStatus">Windows License<span class="requiredIcon">*</span></label>
									<select id="osStatus" name="osStatus" class="form-control chosenSelect">
										<option value="0">Select</option>
										<option value="Activated">Activated</option>
										<option value="Not Activated">Not Activated</option>
									</select>
								  </div>
								<div class="form-group col-md-3">
								  <label for="esetStatus">SOPHOS Status<span class="requiredIcon">*</span></label>
								  <select id="esetStatus" name="esetStatus" class="form-control chosenSelect">
										<option value="0">Select</option>
										<option value="Yes">Yes</option>
										<option value="No">No</option>
									</select>
								</div>
								<div class="form-group col-md-3">
								  <label for="activeDirectory">Active Directory<span class="requiredIcon">*</span></label>
								  <select id="activeDirectory" name="activeDirectory" class="form-control chosenSelect">
										<option value="0">Select</option>
										<option value="Yes">Yes</option>
										<option value="No">No</option>
									</select>
								</div>
								<div class="form-group col-md-3">
									<div id="imageContainer"></div>
								</div>
							  </div>
							 
							  <div class="form-row">
								<div class="form-group col-md-3">
								  <label for="macAddress">Mac Address</label>
								  <input type="text" class="form-control" name="macAddress" placeholder="Mac Address" id="macAddress">
								</div>
								<div class="form-group col-md-3">
								  <label for="printer">Printer</label>
								  <input type="text" class="form-control" name="printer"  placeholder="Model Number" id="printer">
								</div>
								<div class="form-group col-md-3">
								  <label for="scanner">Scanner</label>
								  <input type="text" class="form-control" name="scanner" placeholder="Model Number" id="scanner">
								</div>
								<div class="form-group col-md-2">
									<label for="itemDetailsStatus">Device Status</label>
									<select id="itemDetailsStatus" name="itemDetailsStatus" class="form-control chosenSelect">
										<?php include('inc/statusList.html'); ?>
									</select>
								</div>
								<div class="form-group col-md-3">
									<div id="imageContainer"></div>
								</div>
							  </div>
							  <button type="button" id="addItem" class="btn btn-success">Add Item</button>
							  <button type="button" id="updateItemDetailsButton" class="btn btn-primary">Update</button>
							  <button type="button" id="deleteItem" class="btn btn-danger">Delete</button>
							  <button type="reset" class="btn" id="itemClear">Clear</button>
							</form>
						</div>
					</div>
				  </div> 
				</div>
			  </div>
			  <div class="tab-pane fade" id="v-pills-purchase" role="tabpanel" aria-labelledby="v-pills-purchase-tab">
				<div class="card card-outline-secondary my-4">
				  <div class="card-header">Purchase Details</div>
				  <div class="card-body">
					<div id="purchaseDetailsMessage"></div>
					
				  </div> 
				</div>
			  </div>
			  
			  <div class="tab-pane fade" id="v-pills-vendor" role="tabpanel" aria-labelledby="v-pills-vendor-tab">
				<div class="card card-outline-secondary my-4">
				  <div class="card-header">Vendor Details</div>
				  <div class="card-body">
				  <!-- Div to show the ajax message from validations/db submission -->
				  <div id="vendorDetailsMessage"></div>
					 
				  </div> 
				</div>
			  </div>
			    
			  <div class="tab-pane fade" id="v-pills-sale" role="tabpanel" aria-labelledby="v-pills-sale-tab">
				<div class="card card-outline-secondary my-4">
				  <div class="card-header">Sale Details</div>
				  <div class="card-body">
					<div id="saleDetailsMessage"></div>
					</div> 
				</div>
			  </div>
			  <div class="tab-pane fade" id="v-pills-customer" role="tabpanel" aria-labelledby="v-pills-customer-tab">
				<div class="card card-outline-secondary my-4">
				  <div class="card-header">Customer Details</div>
				  <div class="card-body">
				  <!-- Div to show the ajax message from validations/db submission -->
				  <div id="customerDetailsMessage"></div>
					 
				  </div> 
				</div>
			  </div>
			  
			  <div class="tab-pane fade" id="v-pills-search" role="tabpanel" aria-labelledby="v-pills-search-tab">
				<div class="card card-outline-secondary my-4">
				  <div class="card-header">Search Inventory<button id="searchTablesRefresh" name="searchTablesRefresh" class="btn btn-warning float-right btn-sm">Refresh</button></div>
				  <div class="card-body">										
					<ul class="nav nav-tabs" role="tablist">
						<li class="nav-item">
							<a class="nav-link active" data-toggle="tab" href="#itemSearchTab">Item</a>
						</li>
					</ul>
  
					<!-- Tab panes -->
					<div class="tab-content">
						<div id="itemSearchTab" class="container-fluid tab-pane active">
						  <br>
						  <p>Use the grid below to search all details of items</p>
						  <!-- <a href="#" class="itemDetailsHover" data-toggle="popover" id="10">wwwee</a> -->
							<div class="table-responsive" id="itemDetailsTableDiv"></div>
						</div>
					</div>
				  </div> 
				</div>
			  </div>
			  
			  <div class="tab-pane fade" id="v-pills-reports" role="tabpanel" aria-labelledby="v-pills-reports-tab">
				<div class="card card-outline-secondary my-4">
				  <div class="card-header">Reports<button id="reportsTablesRefresh" name="reportsTablesRefresh" class="btn btn-warning float-right btn-sm">Refresh</button></div>
				  <div class="card-body">										
					<ul class="nav nav-tabs" role="tablist">
						<li class="nav-item">
							<a class="nav-link active" data-toggle="tab" href="#itemReportsTab">Item</a>
						</li>
					</ul>
  
					<!-- Tab panes for reports sections -->
					<div class="tab-content">
						<div id="itemReportsTab" class="container-fluid tab-pane active">
							<br>
							<p>Use the grid below to get reports for items</p>
							<div class="table-responsive" id="itemReportsTableDiv"></div>
						</div>
					</div>
				  </div> 
				</div>
			  </div>
			</div>
		 </div>
	  </div>
    </div>
<?php
	require 'inc/footer.php';
?>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/fontawesome.min.js" integrity="sha512-vF2g7ozd8M2AA8re3eCrfJT2vvrOmIbW9JhodInQHN5Xjg6ec6nJpMJQcwuXm+aOhQze+CrM2rFQLftMtQA+bA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  </body>
</html>
